print("github is such a dick, ridiculous")
print("However, it's pretty fun when you know how to use it")
print("but it's too hard to master")
print("how can I fix conflict")
print("I wanna fix conflict")
print("resolve conflict")
print("creat another conflict")
